# Generated by Django 4.2.13 on 2024-06-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0012_auto_20210523_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpersgifts",
            name="got_bracelet",
            field=models.BooleanField(default=False, verbose_name="Helper got her bracelet"),
        ),
    ]
