# Generated by Django 4.2.13 on 2024-07-06 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0013_helpersgifts_got_bracelet"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftsettings",
            name="required_shirt_points",
            field=models.IntegerField(
                blank=True,
                default=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Shirt Points required to get a shirt",
            ),
        ),
    ]
