# Generated by Django 4.2.13 on 2024-07-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0014_giftsettings_required_shirt_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="is_shirt",
            field=models.BooleanField(default=False, verbose_name="Gift is a Shirt/Textile"),
        ),
    ]
