# Generated by Django 4.2.13 on 2024-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0064_alter_event_url_name_alter_job_job_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="unlimted",
            field=models.BooleanField(default=False, verbose_name="No limit"),
        ),
    ]
