# Generated by Django 4.2.13 on 2024-06-27 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0065_shift_unlimted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shift",
            old_name="unlimted",
            new_name="unlimited",
        ),
    ]
