# Generated by Django 4.2.13 on 2024-07-06 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0067_alter_shift_unlimited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="number",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000000000),
                ],
                verbose_name="Number of helpers",
            ),
        ),
    ]
